import type { Metadata } from "next";

import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

import { Geist, Geist_Mono, Work_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const workSans = Work_Sans({
  variable: "--font-work-sans",

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
 
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  if (!session) redirect("/login");

  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
          rel="stylesheet"
        />
        <link rel="icon" type="image/png" sizes="32x32" href="/uploads/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/uploads/favicon-16x16.png" />
      </head>
      <body
        className={`${workSans.variable} ${workSans.variable} bg-gray-100 antialiased"`}
      >
        <div className="flex min-h-screen">
          <Sidebar />
          <main className="flex-1 p-10">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
